### ISSUE TITLE
Can't download caption

### ISSUE THREAD

**Issue by isneezy** [gielcobben/CaptionWebsite#6]
When i try to download caption noting happens, even when i try to click on the drop down button.

**Aditional info**
Browser: Firefox58 0b11 (64Bit)
Console log:
```
unreachable code after return statement                        js:64:1196
```

**Comment by gielcobben** [comment]
@isneezy It seems to be a bug in the Google tag-manager script and is known by Google and Firefox. Please consider downloading the latest version from: https://github.com/gielcobben/caption/releases
